// Styles
import "@/src/app/globals.scss";

// Utilities
import React from "react";
import type { Metadata } from "next";
import { Montserrat, Bitter } from "next/font/google";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

// Components
import Header from "@/src/components/header/header";
import Footer from "@/src/components/footer/footer";

const montserrat = Montserrat({
   weight: "800",
   subsets: ["latin"],
   variable: "--montserrat-font-family",
   display: "swap",
});

const bitter = Bitter({
   weight: "500",
   variable: "--bitter-font-family",
   subsets: ["latin"],
   display: "swap",
});

export const metadata: Metadata = {
   title: "Re:rise",
   description: "Generated by create next app",
};

export default async function BaseLayout({
   children,
   locale,
}: Readonly<{
   children: React.ReactNode;
   locale: string;
}>) {
   // Providing all messages to the client
   // side is the easiest way to get started
   const messages = await getMessages();
   return (
      <html
         lang={locale}
         className={`${montserrat.variable} ${bitter.variable}`}
      >
         <body>
            <NextIntlClientProvider messages={messages}>
               <Header />
               {children}
               <Footer />
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
