// Utilities
import type { Metadata } from "next";

// Components
import Header from "@/components/header/header";

export const metadata: Metadata = {
   title: "Re:rise",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <Header />
            {children}
         </body>
      </html>
   );
}
