// Styles
import "./globals.scss";

// Utilities
import React from "react";
import type { Metadata } from "next";
import { Montserrat, Bitter } from "next/font/google";

// Components
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const montserrat = Montserrat({
   weight: "800",
   subsets: ["latin"],
   variable: "--montserrat-font-family",
   display: "swap",
});

const bitter = Bitter({
   weight: "500",
   variable: "--bitter-font-family",
   subsets: ["latin"],
   display: "swap",
});

export const metadata: Metadata = {
   title: "Re:rise",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="ro" className={`${montserrat.variable} ${bitter.variable}`}>
         <body>
            <Header />
            {children}
            <Footer />
         </body>
      </html>
   );
}
